name: ng
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.10
  - pandas
  - numpy
  - scipy
  - scikit-learn
  - biopython
  - streamlit
  - altair
  - matplotlib-base
  - seaborn-base
  - plotly
  - requests
  - pyyaml
  - python-dateutil
  - rich
  - psutil
  - pip
  - fastqc
  - fastp
  - minimap2
  - samtools
  - bcftools
  - kraken2
  - blast
  - ncbi-datasets-cli
  - mlst
  - mash
  - rapidnj
  - ska2=0.5.1
  - spades
  - pip:
    - vega-datasets
    - newick
    - pyfastx
    - scikit-image
    - pyngoST
    - chewbbaca
